name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly scan on Sunday
  workflow_dispatch:      # Allow manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP Baseline Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Building Docker Image
        run: docker build -t apps-download-web .

      - name: Run Docker Container
        run: docker run -d -p 8080:80 apps-download-web

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
